import "../styles/globals.css";
import { Provider } from "react-redux";
import { globalStore } from "../src/store/store";
import { createTheme, ThemeProvider } from "@mui/material";
import React from "react";
import Head from "next/head";
import { Box } from "@mui/material";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import { ThemeColor } from "../src/config/constants";

const theme = createTheme({
  components: {
    MuiButton: {
      styleOverrides: {
        disableElevation: true,
        borderRadius: 50,
      },
      defaultProps: {
        disableElevation: true,
        disableFocusRipple: true,
        disableRipple: true,
      },
    },
  },
  typography: {
    fontFamily: [
      "-apple-system",
      "BlinkMacSystemFont",
      '"Segoe UI"',
      "Roboto",
      '"Helvetica Neue"',
      "Arial",
      "sans-serif",
      '"Apple Color Emoji"',
      '"Segoe UI Emoji"',
      '"Segoe UI Symbol"',
    ].join(","),
  },
  palette: {
    primary: {
      main: ThemeColor.primary,
    },
  },
  shape: {
    borderRadius: 50,
  },
});

function MyApp({ Component, pageProps }) {
  return (
    <Provider store={globalStore}>
      <ThemeProvider theme={theme}>
        <Head>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
          />

          <title>Hotel Booking</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
        </Head>

        <Box style={{ height: "100vh" }}>
          <Component {...pageProps} />
        </Box>
      </ThemeProvider>
    </Provider>
  );
}

export default MyApp;
