import "../styles/globals.css";
import { Provider } from "react-redux";
import { globalStore } from "../src/store/store";
import { createTheme, ThemeProvider } from "@mui/material";
import React, { useEffect } from "react";
import Head from "next/head";
import { Box } from "@mui/material";

import { motion } from "framer-motion";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import { GOOGLE_APP_ID, ThemeColor } from "../src/config/constants";
import { GoogleOAuthProvider } from "@react-oauth/google";

const theme = createTheme({
  components: {
    MuiButton: {
      styleOverrides: {
        disableElevation: true,
        borderRadius: 50,
      },
      defaultProps: {
        disableElevation: true,
        disableFocusRipple: true,
        disableRipple: true,
      },
    },
  },
  typography: {
    fontFamily: [
      "-apple-system",
      "BlinkMacSystemFont",
      '"Segoe UI"',
      "Roboto",
      '"Helvetica Neue"',
      "Arial",
      "sans-serif",
      '"Apple Color Emoji"',
      '"Segoe UI Emoji"',
      '"Segoe UI Symbol"',
    ].join(","),
  },
  palette: {
    primary: {
      main: ThemeColor.primary,
    },
  },
  shape: {
    borderRadius: 50,
  },
});

function MyApp({ Component, pageProps, router }) {
  return (
    <Provider store={globalStore}>
      <ThemeProvider theme={theme}>
        <Head>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
          />

          <title>Hotel Booking</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
          <script
            src="https://apis.google.com/js/platform.js?onload=init"
            async
            defer
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `
          
           gapi.load('auth2', function() {
    /* Ready. Make a call to gapi.auth2.init or some other API */
  });
          `,
            }}
          />
        </Head>

        <motion.div
          key={router.route}
          initial="initial"
          animate="animate"
          variants={{
            initial: {
              opacity: 0,
            },
            animate: {
              opacity: 1,
            },
          }}
        >
          <Box style={{ height: "100vh" }}>
            <GoogleOAuthProvider clientId={GOOGLE_APP_ID}>
              <Component {...pageProps} />
            </GoogleOAuthProvider>
          </Box>
        </motion.div>
      </ThemeProvider>
    </Provider>
  );
}

export default MyApp;
